# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jarvis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jarvis.proto',
  package='jarvis',
  serialized_pb=_b('\n\x0cjarvis.proto\x12\x06jarvis\"O\n\tParameter\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\t\x12&\n\x04type\x18\x03 \x02(\x0e\x32\x10.jarvis.DataType:\x06STRING\">\n\x06Intent\x12\x0e\n\x06\x61\x63tion\x18\x01 \x02(\t\x12$\n\tparameter\x18\x02 \x03(\x0b\x32\x11.jarvis.Parameter\"U\n\x05Route\x12\x0e\n\x06\x61\x63tion\x18\x01 \x02(\t\x12\x15\n\rreq_parameter\x18\x02 \x03(\t\x12\x15\n\ropt_parameter\x18\x03 \x03(\t\x12\x0e\n\x06target\x18\x04 \x02(\t\"9\n\x08Manifest\x12\x0f\n\x07\x61ppname\x18\x01 \x02(\t\x12\x1c\n\x05route\x18\x02 \x03(\x0b\x32\r.jarvis.Route*3\n\x08\x44\x61taType\x12\x07\n\x03URI\x10\x01\x12\n\n\x06STRING\x10\x02\x12\x07\n\x03INT\x10\x03\x12\t\n\x05\x46LOAT\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='jarvis.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='URI', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=315,
  serialized_end=366,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
URI = 1
STRING = 2
INT = 3
FLOAT = 4



_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='jarvis.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='jarvis.Parameter.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='jarvis.Parameter.data', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='jarvis.Parameter.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=103,
)


_INTENT = _descriptor.Descriptor(
  name='Intent',
  full_name='jarvis.Intent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='jarvis.Intent.action', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameter', full_name='jarvis.Intent.parameter', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=167,
)


_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='jarvis.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='jarvis.Route.action', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_parameter', full_name='jarvis.Route.req_parameter', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opt_parameter', full_name='jarvis.Route.opt_parameter', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='jarvis.Route.target', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=254,
)


_MANIFEST = _descriptor.Descriptor(
  name='Manifest',
  full_name='jarvis.Manifest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appname', full_name='jarvis.Manifest.appname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='route', full_name='jarvis.Manifest.route', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=313,
)

_PARAMETER.fields_by_name['type'].enum_type = _DATATYPE
_INTENT.fields_by_name['parameter'].message_type = _PARAMETER
_MANIFEST.fields_by_name['route'].message_type = _ROUTE
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['Intent'] = _INTENT
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.message_types_by_name['Manifest'] = _MANIFEST
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETER,
  __module__ = 'jarvis_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.Parameter)
  ))
_sym_db.RegisterMessage(Parameter)

Intent = _reflection.GeneratedProtocolMessageType('Intent', (_message.Message,), dict(
  DESCRIPTOR = _INTENT,
  __module__ = 'jarvis_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.Intent)
  ))
_sym_db.RegisterMessage(Intent)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), dict(
  DESCRIPTOR = _ROUTE,
  __module__ = 'jarvis_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.Route)
  ))
_sym_db.RegisterMessage(Route)

Manifest = _reflection.GeneratedProtocolMessageType('Manifest', (_message.Message,), dict(
  DESCRIPTOR = _MANIFEST,
  __module__ = 'jarvis_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.Manifest)
  ))
_sym_db.RegisterMessage(Manifest)


# @@protoc_insertion_point(module_scope)
