# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='conf.proto',
  package='jarvis',
  serialized_pb=_b('\n\nconf.proto\x12\x06jarvis\"3\n\x07\x41udioIO\x12\x0c\n\x04host\x18\x01 \x02(\t\x12\x0c\n\x04port\x18\x02 \x02(\x05\x12\x0c\n\x04name\x18\x03 \x02(\t\"$\n\x06Server\x12\x0c\n\x04host\x18\x01 \x02(\t\x12\x0c\n\x04port\x18\x02 \x02(\x05\"\xbb\x01\n\nJarvisConf\x12\x10\n\x08root_dir\x18\x06 \x02(\t\x12\x0f\n\x07\x61pp_dir\x18\x01 \x02(\t\x12\x1e\n\x06memory\x18\x02 \x02(\x0b\x32\x0e.jarvis.Server\x12\x1d\n\x05state\x18\x03 \x02(\x0b\x32\x0e.jarvis.Server\x12$\n\x0b\x61udio_input\x18\x04 \x03(\x0b\x32\x0f.jarvis.AudioIO\x12%\n\x0c\x61udio_output\x18\x05 \x03(\x0b\x32\x0f.jarvis.AudioIO')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_AUDIOIO = _descriptor.Descriptor(
  name='AudioIO',
  full_name='jarvis.AudioIO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='jarvis.AudioIO.host', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='jarvis.AudioIO.port', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='jarvis.AudioIO.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=73,
)


_SERVER = _descriptor.Descriptor(
  name='Server',
  full_name='jarvis.Server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='jarvis.Server.host', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='jarvis.Server.port', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=111,
)


_JARVISCONF = _descriptor.Descriptor(
  name='JarvisConf',
  full_name='jarvis.JarvisConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root_dir', full_name='jarvis.JarvisConf.root_dir', index=0,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_dir', full_name='jarvis.JarvisConf.app_dir', index=1,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='memory', full_name='jarvis.JarvisConf.memory', index=2,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='jarvis.JarvisConf.state', index=3,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='audio_input', full_name='jarvis.JarvisConf.audio_input', index=4,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='audio_output', full_name='jarvis.JarvisConf.audio_output', index=5,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=301,
)

_JARVISCONF.fields_by_name['memory'].message_type = _SERVER
_JARVISCONF.fields_by_name['state'].message_type = _SERVER
_JARVISCONF.fields_by_name['audio_input'].message_type = _AUDIOIO
_JARVISCONF.fields_by_name['audio_output'].message_type = _AUDIOIO
DESCRIPTOR.message_types_by_name['AudioIO'] = _AUDIOIO
DESCRIPTOR.message_types_by_name['Server'] = _SERVER
DESCRIPTOR.message_types_by_name['JarvisConf'] = _JARVISCONF

AudioIO = _reflection.GeneratedProtocolMessageType('AudioIO', (_message.Message,), dict(
  DESCRIPTOR = _AUDIOIO,
  __module__ = 'conf_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.AudioIO)
  ))
_sym_db.RegisterMessage(AudioIO)

Server = _reflection.GeneratedProtocolMessageType('Server', (_message.Message,), dict(
  DESCRIPTOR = _SERVER,
  __module__ = 'conf_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.Server)
  ))
_sym_db.RegisterMessage(Server)

JarvisConf = _reflection.GeneratedProtocolMessageType('JarvisConf', (_message.Message,), dict(
  DESCRIPTOR = _JARVISCONF,
  __module__ = 'conf_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.JarvisConf)
  ))
_sym_db.RegisterMessage(JarvisConf)


# @@protoc_insertion_point(module_scope)
